//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlShortenerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Url
    {
        public string Id { get; set; }
        public string LongUrl { get; set; }
        public string ShortUrl { get; set; }
        public int Key { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool Expires { get; set; }
        public Nullable<System.DateTime> ExpiresAt { get; set; }
        public int MaxClicks { get; set; }
        public int CurrentClicks { get; set; }
        public bool IsActive { get; set; }
    }
}
