//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlShortenerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Url
    {
        public string Id { get; set; }
        public string LongUrl { get; set; }
        public string ShortUrl { get; set; }
        public string UserId { get; set; }
        public string CampaignId { get; set; }
        public int Token { get; set; }
        public int Clicks { get; set; }
        public int MaxClicks { get; set; }
        public bool Expires { get; set; }
        public Nullable<System.DateTime> ExpiresAt { get; set; }
        public bool HasExpired { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string IPAddress { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Campaign Campaign { get; set; }
    }
}
