//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrlShortenerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlsIPAddress
    {
        public string UrlId { get; set; }
        public string IPAddressId { get; set; }
        public System.DateTime ClickedAt { get; set; }
    
        public virtual ClientIPAddress ClientIPAddress { get; set; }
        public virtual Url Url { get; set; }
    }
}
